namespace: food-qa

backend:
  image: ghcr.io/novablazing/food-backend
  tag: qa
  imagePullPolicy: Always
  replicas: 2
  env:
    databaseUrl: "mongodb://mongouser:mongopass@mongodb-service:27017/?authSource=admin"
    databaseName: "ead_qa"
    databaseCollection: "ead_qa_2024"

frontend:
  image: ghcr.io/novablazing/food-frontend
  tag: qa
  imagePullPolicy: Always
  replicas: 2
  hpa:
    enabled: true
    minReplicas: 2
    maxReplicas: 4
    targetCPUUtilizationPercentage: 70

mongodb:
  replicas: 1
  auth:
    rootUsername: mongouser
    rootPassword: mongopass
