namespace: food-prod

backend:
  image: ghcr.io/OWNER/food-backend
  tag: v1
  imagePullPolicy: IfNotPresent
  replicas: 3
  env:
    databaseUrl: "mongodb://mongodb-service:27017/"
    databaseName: "ead_ca2"
    databaseCollection: "ead_2024"

frontend:
  image: ghcr.io/OWNER/food-frontend
  tag: v1
  imagePullPolicy: IfNotPresent
  replicas: 3

mongodb:
  replicas: 1
