namespace: food-prod

imagePullSecret:
  username: ""
  password: ""

backend:
  image: ghcr.io/novablazing/food-backend
  tag: v1
  imagePullPolicy: IfNotPresent
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  env:
    databaseUrl: "mongodb://mongouser:mongopass@mongodb-service:27017/?authSource=admin"
    databaseName: "ead_prod"
    databaseCollection: "ead_prod_2024"

frontend:
  image: ghcr.io/novablazing/food-frontend
  tag: v1
  imagePullPolicy: IfNotPresent
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  hpa:
    enabled: true
    minReplicas: 3
    maxReplicas: 6
    targetCPUUtilizationPercentage: 70

mongodb:
  replicas: 1
  auth:
    rootUsername: mongouser
    rootPassword: mongopass
