namespace: food-prod

imagePullSecret:
  username: ""
  password: ""

backend:
  image: ghcr.io/novablazing/food-backend
  tag: v1
  imagePullPolicy: IfNotPresent
  replicas: 3
  env:
    databaseUrl: "mongodb://mongodb-service:27017/"
    databaseName: "ead_ca2"
    databaseCollection: "ead_2024"

frontend:
  image: ghcr.io/novablazing/food-frontend
  tag: v1
  imagePullPolicy: IfNotPresent
  replicas: 3
  hpa:
    enabled: true
    minReplicas: 3
    maxReplicas: 6
    targetCPUUtilizationPercentage: 70

mongodb:
  replicas: 1
