apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.backend.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.backend.name }}
spec:
  replicas: {{ .Values.backend.replicas }}
  {{- if .Values.backend.strategy }}
  strategy:
    type: {{ .Values.backend.strategy.type }}
    {{- if eq .Values.backend.strategy.type "RollingUpdate" }}
    rollingUpdate:
      maxUnavailable: {{ .Values.backend.strategy.rollingUpdate.maxUnavailable }}
      maxSurge: {{ .Values.backend.strategy.rollingUpdate.maxSurge }}
    {{- end }}
  {{- end }}
  selector:
    matchLabels:
      app: {{ .Values.backend.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.backend.name }}
    spec:
      imagePullSecrets:
      - name: ghcr-secret
      containers:
      - name: {{ .Values.backend.name }}
        image: {{ .Values.backend.image }}:{{ .Values.backend.tag }}
        imagePullPolicy: {{ .Values.backend.imagePullPolicy }}
        ports:
        - containerPort: {{ .Values.backend.port }}
        env:
        - name: DATABASE_URL
          value: {{ .Values.backend.env.databaseUrl | quote }}
        - name: DATABASE_NAME
          value: {{ .Values.backend.env.databaseName | quote }}
        - name: DATABASE_COLLECTION
          value: {{ .Values.backend.env.databaseCollection | quote }}
        livenessProbe:
          httpGet:
            path: {{ .Values.backend.livenessProbe.httpGet.path }}
            port: {{ .Values.backend.livenessProbe.httpGet.port }}
          initialDelaySeconds: {{ .Values.backend.livenessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.backend.livenessProbe.periodSeconds }}
          timeoutSeconds: {{ .Values.backend.livenessProbe.timeoutSeconds }}
          failureThreshold: {{ .Values.backend.livenessProbe.failureThreshold }}
        readinessProbe:
          httpGet:
            path: {{ .Values.backend.readinessProbe.httpGet.path }}
            port: {{ .Values.backend.readinessProbe.httpGet.port }}
          initialDelaySeconds: {{ .Values.backend.readinessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.backend.readinessProbe.periodSeconds }}
          timeoutSeconds: {{ .Values.backend.readinessProbe.timeoutSeconds }}
          failureThreshold: {{ .Values.backend.readinessProbe.failureThreshold }}
