apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.frontend.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.frontend.name }}
spec:
  {{- if not .Values.frontend.hpa.enabled }}
  replicas: {{ .Values.frontend.replicas }}
  {{- end }}
  selector:
    matchLabels:
      app: {{ .Values.frontend.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.frontend.name }}
    spec:
      imagePullSecrets:
      - name: ghcr-secret
      containers:
      - name: {{ .Values.frontend.name }}
        image: {{ .Values.frontend.image }}:{{ .Values.frontend.tag }}
        imagePullPolicy: {{ .Values.frontend.imagePullPolicy }}
        ports:
        - containerPort: {{ .Values.frontend.port }}
        resources:
          requests:
            cpu: {{ .Values.frontend.resources.requests.cpu }}
            memory: {{ .Values.frontend.resources.requests.memory }}
          limits:
            cpu: {{ .Values.frontend.resources.limits.cpu }}
            memory: {{ .Values.frontend.resources.limits.memory }}
        livenessProbe:
          tcpSocket:
            port: {{ .Values.frontend.livenessProbe.tcpSocket.port }}
          initialDelaySeconds: {{ .Values.frontend.livenessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.frontend.livenessProbe.periodSeconds }}
          timeoutSeconds: {{ .Values.frontend.livenessProbe.timeoutSeconds }}
          failureThreshold: {{ .Values.frontend.livenessProbe.failureThreshold }}
        readinessProbe:
          tcpSocket:
            port: {{ .Values.frontend.readinessProbe.tcpSocket.port }}
          initialDelaySeconds: {{ .Values.frontend.readinessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.frontend.readinessProbe.periodSeconds }}
          timeoutSeconds: {{ .Values.frontend.readinessProbe.timeoutSeconds }}
          failureThreshold: {{ .Values.frontend.readinessProbe.failureThreshold }}
