apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.mongodb.name }}-pv
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.mongodb.name }}
spec:
  capacity:
    storage: {{ .Values.mongodb.storage.size }}
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: {{ .Values.mongodb.storage.storageClassName }}
  hostPath:
    path: {{ .Values.mongodb.storage.hostPath }}
    type: DirectoryOrCreate
