apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  mongodb-root-username: {{ .Values.mongodb.auth.rootUsername | b64enc | quote }}
  mongodb-root-password: {{ .Values.mongodb.auth.rootPassword | b64enc | quote }}
