databaseUrl=${DATABASE_URL:mongodb://mongodb-service:27017/}
databaseName=${DATABASE_NAME:ead_ca2}
databaseCollection=${DATABASE_COLLECTION:ead_2024}

# Enable the env endpoint
management.endpoints.web.exposure.include=env,health

org.springframework.web.servlet.mvc.method.annotation=DEBUG
log4j.logger.org.springframework.web.servlet.mvc.method.annotation=DEBUG, console
logging.level.org.springframework.web= DEBUG
spring.http.log-request-details=true
